<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Category;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function save(Category $category)
    {
        $this->_em->persist($category);
        $this->_em->flush();
    }

    public function update(Category $category)
    {
        $this->_em->merge($category);
        $this->_em->flush();
    }

    public function remove(Category $category)
    {
        $this->_em->remove($category);
        $this->_em->flush();
    }
}
