<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Country;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends \Doctrine\ORM\EntityRepository
{
    public function save(Country $country)
    {
        $this->_em->persist($country);
        $this->_em->flush();
    }

    public function update(Country $country)
    {
        $this->_em->merge($country);
        $this->_em->flush();
    }

    public function remove(Country $country)
    {
        $this->_em->remove($country);
        $this->_em->flush();
    }
}
