<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Currency;

/**
 * CurrencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrencyRepository extends \Doctrine\ORM\EntityRepository
{
	public function save(Currency $currency)
    {
        $this->_em->persist($currency);
        $this->_em->flush();
    }

    public function update(Currency $currency)
    {
        $this->_em->merge($currency);
        $this->_em->flush();
    }

    public function remove(Currency $currency)
    {
        $this->_em->remove($currency);
        $this->_em->flush();
    }
}
