<?php

namespace AppBundle\Repository;

/**
 * ImageSizeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageSizeRepository extends \Doctrine\ORM\EntityRepository
{
}
