<?php

namespace AppBundle\Repository;

/**
 * ProductImageSizeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductImageSizeRepository extends \Doctrine\ORM\EntityRepository
{
}
