<?php

namespace AppBundle\Repository;

/**
 * ProductImageLanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductImageLanguageRepository extends \Doctrine\ORM\EntityRepository
{
}
