<?php

namespace AppBundle\Repository;

/**
 * ProductLanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductLanguageRepository extends \Doctrine\ORM\EntityRepository
{
}
