<?php

namespace AppBundle\Repository;

use AppBundle\Entity\ProductPropertyLanguage;

/**
 * ProductPropertyLanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductPropertyLanguageRepository extends \Doctrine\ORM\EntityRepository
{
    public function save(ProductPropertyLanguage $productProperty)
    {
        $this->_em->persist($productProperty);
        $this->_em->flush();
    }

    public function update(ProductPropertyLanguage $productProperty)
    {
        $this->_em->merge($productProperty);
        $this->_em->flush();
    }

    public function remove(ProductPropertyLanguage $productProperty)
    {
        $this->_em->remove($productProperty);
        $this->_em->flush();
    }
}
