<?php

namespace AppBundle\Repository;

use AppBundle\Entity\ProductProperty;

/**
 * ProductPropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductPropertyRepository extends \Doctrine\ORM\EntityRepository
{
    public function save(ProductProperty $productProperty)
    {
        $this->_em->persist($productProperty);
        $this->_em->flush();
    }

    public function update(ProductProperty $productProperty)
    {
        $this->_em->merge($productProperty);
        $this->_em->flush();
    }

    public function remove(ProductProperty $productProperty)
    {
        $this->_em->remove($productProperty);
        $this->_em->flush();
    }
}
