<?php

namespace AppBundle\Repository;

/**
 * ProductPropertiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductPropertiesRepository extends \Doctrine\ORM\EntityRepository
{
}
