<?php

namespace AppBundle\Repository;

/**
 * ProductPropertyValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductPropertyValueRepository extends \Doctrine\ORM\EntityRepository
{

    public function deleteById(int $id)
    {
        $qb = $this->createQueryBuilder('pv');
        $qb->delete();
        $qb->where('pv.id = :id');
        $qb->setParameter('id', $id);

        $qb->getQuery()
            ->execute();
        //$qb->execute();
    }
}
