<?php

namespace AppBundle\Repository;

/**
 * ProductStorageGroupPricesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductStorageGroupPriceRepository extends \Doctrine\ORM\EntityRepository
{
}
