<?php

namespace AppBundle\Repository;

/**
 * ProductFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductFileRepository extends \Doctrine\ORM\EntityRepository
{
}
