<?php

namespace AppBundle\Repository;

/**
 * StorageQuantityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StorageQuantityRepository extends \Doctrine\ORM\EntityRepository
{
}
